language: generic
sudo: required
dist: trusty

matrix:
  fast_finish: true
  include:
    - os: osx
      compiler: clang
      env: CCOMPILER='clang' CXXCOMPILER='clang++'

    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7', 'cmake', 'realpath']
      env: CCOMPILER='gcc-7' CXXCOMPILER='g++-7'

    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6', 'cmake', 'realpath']
      env: CCOMPILER='gcc-6' CXXCOMPILER='g++-6'

    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'cmake', 'realpath']
      env: CCOMPILER='gcc-5' CXXCOMPILER='g++-5'

    # Waiting on Travis whitelisting clang-4.0

before_install:
  - export CC=${CCOMPILER} CXX=${CXXCOMPILER}

install:
  - git clone --depth 1 --branch v0.14.1 https://github.com/mapbox/mason.git .mason
  - mkdir build
  - pushd build
  - cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON ..
  - cmake --build .
  - popd
