language: cpp
sudo: false
matrix:
    include:
        - os: linux
          compiler: clang
          env: BUILD_TYPE=Dev
        - os: linux
          compiler: clang
          env: BUILD_TYPE=Release
        - os: linux
          compiler: gcc
          env: BUILD_TYPE=Dev
        - os: linux
          compiler: gcc
          env: BUILD_TYPE=Release
        - os: osx
          compiler: clang
          env: BUILD_TYPE=Dev
        - os: osx
          compiler: clang
          env: BUILD_TYPE=Release

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - boost-latest
        packages:
            - g++-4.8
            - gcc-4.8
            - libboost1.55-dev

install:
    - git clone --quiet --depth 1 https://github.com/osmcode/libosmium.git ../libosmium
    - git clone --quiet --depth 1 https://github.com/facebook/rocksdb.git ../rocksdb

script:
    - scripts/travis_script.sh

